import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { FaArrowRight, FaDatabase, FaFileAlt, FaHospital, FaKey, FaPlus, FaShieldAlt, FaUserPlus, FaUsers, FaTint, FaCheckCircle } from "react-icons/fa";
import StatusBadge from "../../components/StatusBadge";
import { useAppState } from "../../context/useAppState";
import { operationalSummary } from "../../utils/analytics";
import { aggregateByGroup } from "../../utils/networkInventory";

function SectionHeading({ title, description, action }) { return <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div>{action}</div>; }
export default function AdminDashboard({ onNavigate }) {
  const { adminUsers=[], hospitals=[], bloodRequests=[], patients=[], donors=[], networkInventory=[], auditLogs=[], user } = useAppState();
  const stock = aggregateByGroup(networkInventory).map((x) => ({ type: x.bloodGroup, quantity: x.available, threshold: x.bloodGroup.includes("-") ? 5 : 10 }));
  const s=operationalSummary({patients,bloodRequests,donors,stock,hospitals});
  const pendingApprovals=adminUsers.filter(u=>u.status==="Pending").length + hospitals.filter(h=>h.status==="Pending").length;
  const cards=[["Total users",adminUsers.length,"Unique registered accounts",FaUsers],["Hospitals",hospitals.length,"Registered facilities",FaHospital],["Donors",donors.length,"Unique donor records",FaUserPlus],["Blood units",s.stock.totalUnits,"Current stock",FaTint],["Pending approvals",pendingApprovals,"Accounts or hospitals awaiting review",FaKey]];
  const activity=adminUsers.slice(-7).map((u,i)=>({day:`${i+1}`,users:i+1,requests:0}));

  const hour = new Date().getHours();
  const timeGreeting = hour < 12 ? "Good morning" : hour < 17 ? "Good afternoon" : "Good evening";
  const userName = user?.name || user?.username || user?.email?.split("@")[0] || "Administrator";

  return <div className="space-y-7 pb-6">
    <section className="rounded-[2rem] bg-[#171b2c] px-6 py-7 text-white shadow-xl sm:px-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-semibold"><FaShieldAlt/> ZNBTS platform control centre</div><h1 className="mt-4 text-3xl font-bold">{timeGreeting}, {userName}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Manage users, Copperbelt hospitals, approvals, security and operational data.</p></div><div className="rounded-2xl border border-emerald-300/20 bg-emerald-400/10 px-4 py-3"><p className="text-sm font-semibold">Frontend operational</p><p className="text-xs text-slate-300">Ready for API/database integration.</p></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label,value,note,Icon], index)=><article key={label} onClick={()=>onNavigate(["/admin/users","/admin/hospitals","/donors","/network/inventory","/admin/hospitals"][index])} role="button" tabIndex={0} onKeyDown={(e)=>e.key==="Enter"&&onNavigate(["/admin/users","/admin/hospitals","/donors","/network/inventory","/admin/hospitals"][index])} className="cursor-pointer rounded-3xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-[#a51d2d] hover:shadow-md"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div><span className="grid h-11 w-11 place-items-center rounded-2xl bg-rose-50 text-rose-700"><Icon/></span></div><p className="mt-4 text-xs font-medium text-slate-500">{note}</p></article>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.45fr_1fr]"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><SectionHeading title="Operational overview" description="Counts are derived from the same current state used by operational dashboards." action={<button onClick={()=>onNavigate("/admin/reports")} className="text-sm font-semibold text-[#8f1220]">View reports <FaArrowRight className="inline"/></button>}/><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-sm text-slate-500">Patients</p><p className="mt-1 text-2xl font-bold">{s.patients.total}</p><p className="text-xs text-slate-500">Male {s.patients.male} · Female {s.patients.female} · Other {s.patients.other}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-sm text-slate-500">Blood requests</p><p className="mt-1 text-2xl font-bold">{s.requests.total}</p><p className="text-xs text-slate-500">Pending {s.requests.pending} · Approved {s.requests.approved} · Completed {s.requests.completed}</p></div></div><div className="mt-5 h-52"><ResponsiveContainer width="100%" height="100%"><BarChart data={activity}><CartesianGrid vertical={false} stroke="#e2e8f0"/><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="users" name="Account records" fill="#9d1b2b" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></article><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><SectionHeading title="Attention required" description="Items that can be acted on now."/><div className="mt-5 space-y-3"><button onClick={()=>onNavigate("/admin/users")} className="w-full rounded-2xl border border-amber-200 bg-amber-50 p-4 text-left"><p className="font-bold text-amber-900">{pendingApprovals} pending approvals</p><p className="mt-1 text-xs text-amber-800">Review account and hospital registration requests.</p></button><button onClick={()=>onNavigate("/regional/emergency")} className="w-full rounded-2xl border border-red-200 bg-red-50 p-4 text-left"><p className="font-bold text-red-900">{s.requests.critical} critical requests</p><p className="mt-1 text-xs text-red-800">Open the regional escalation queue.</p></button><button onClick={()=>onNavigate("/regional/inventory")} className="w-full rounded-2xl border border-orange-200 bg-orange-50 p-4 text-left"><p className="font-bold text-orange-900">{s.stock.lowStock} low-stock groups</p><p className="mt-1 text-xs text-orange-800">Review current blood inventory.</p></button></div></article></section>
    <section className="grid gap-6 xl:grid-cols-[1.45fr_1fr]"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><SectionHeading title="User management" description="Current registered accounts." action={<button onClick={()=>onNavigate("/admin/users")} className="rounded-xl bg-[#8f1220] px-3 py-2 text-sm font-semibold text-white"><FaPlus className="mr-1 inline"/> Manage users</button>}/><div className="mt-5 overflow-x-auto"><table className="min-w-full text-left"><thead className="border-b border-slate-100 text-xs uppercase tracking-wide text-slate-400"><tr><th className="pb-3">User</th><th className="pb-3">Role</th><th className="pb-3">Hospital</th><th className="pb-3">Status</th></tr></thead><tbody>{adminUsers.slice(-8).reverse().map(u=><tr key={u.id} className="border-b border-slate-50"><td className="py-3"><p className="font-semibold">{u.name}</p><p className="text-xs text-slate-500">{u.email}</p></td><td className="py-3 text-sm">{u.role}</td><td className="py-3 text-sm">{u.hospital || "—"}</td><td className="py-3"><StatusBadge status={u.status==="Active"?"success":"warning"}>{u.status}</StatusBadge></td></tr>)}</tbody></table></div></article><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><SectionHeading title="Audit timeline" description="Latest application events." action={<button onClick={()=>onNavigate("/admin/audit-logs")} className="text-sm font-semibold text-[#8f1220]">View all</button>}/><ol className="mt-5 space-y-4">{auditLogs.slice(0,6).map(item=><li key={item.id} className="flex gap-3"><span className="mt-1 h-3 w-3 shrink-0 rounded-full bg-[#a51d2d]"/><div><p className="text-sm font-bold">{item.event}</p><p className="text-xs text-slate-500">{item.detail} · {item.time}</p></div></li>)}</ol></article></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><SectionHeading title="Quick actions" description="Every control opens a real workflow."/><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[["Manage Users",FaUserPlus,"/admin/users"],["Register Hospital",FaHospital,"/admin/hospitals"],["Approve Requests",FaCheckCircle,"/regional/emergency"],["Adjust Stock",FaTint,"/regional/inventory"],["View Reports",FaFileAlt,"/admin/reports"],["Run Backup",FaDatabase,"/admin/backup"]].map(([label,Icon,path])=><button key={label} type="button" onClick={()=>onNavigate(path)} className="flex min-h-16 items-center gap-3 rounded-2xl border border-slate-200 p-4 text-left hover:border-[#a51d2d] hover:bg-rose-50"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-rose-50 text-[#941625]"><Icon/></span><span className="font-semibold text-slate-800">{label}</span><FaArrowRight className="ml-auto text-slate-400"/></button>)}</div></section>
  </div>;
}
