import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { FaArrowRight, FaBell,FaTint, FaCheckCircle, FaDatabase, FaFileAlt, FaHospital, FaKey, FaPlus, FaServer, FaShieldAlt, FaUserPlus, FaUsers } from "react-icons/fa";
import StatusBadge from "../../components/StatusBadge";

const cards = [
  { label: "Total users", value: "1,284", change: "+8.4% this month", icon: FaUsers, tone: "bg-violet-50 text-violet-600" },
  { label: "Hospitals", value: "42", change: "+3 onboarded", icon: FaHospital, tone: "bg-blue-50 text-blue-600" },
  { label: "Online users", value: "218", change: "17 active now", icon: FaUserPlus, tone: "bg-emerald-50 text-emerald-600" },
  { label: "System health", value: "99.98%", change: "All services operational", icon: FaShieldAlt, tone: "bg-rose-50 text-rose-600" },
  { label: "Pending approvals", value: "14", change: "Requires review", icon: FaKey, tone: "bg-amber-50 text-amber-600" },
];
const usage = [{ day: "Mon", users: 182, requests: 86 }, { day: "Tue", users: 215, requests: 104 }, { day: "Wed", users: 198, requests: 93 }, { day: "Thu", users: 242, requests: 128 }, { day: "Fri", users: 268, requests: 149 }, { day: "Sat", users: 174, requests: 75 }, { day: "Sun", users: 161, requests: 68 }];
const users = [{ name: "Dr. Chola Banda", email: "chola@ndola.org", role: "Hospital Staff", hospital: "Ndola Teaching Hospital", status: "Active" }, { name: "Mwansa Tembo", email: "mwansa@centre.zm", role: "Regional Centre", hospital: "Copperbelt Blood Centre", status: "Active" }, { name: "Ruth Phiri", email: "ruth.phiri@mail.com", role: "Blood Donor", hospital: "—", status: "Pending" }, { name: "David Mwila", email: "david@umulopa.org", role: "System Administrator", hospital: "UMULOPA", status: "Active" }];
const activity = [{ event: "Role updated", detail: "Dr. Chola Banda assigned Hospital Staff", time: "8 min ago", status: "info" }, { event: "Hospital approved", detail: "Kabwe General Hospital joined the network", time: "24 min ago", status: "success" }, { event: "Permission review", detail: "14 user access requests are pending", time: "1 hr ago", status: "warning" }, { event: "Security policy changed", detail: "MFA enforcement was enabled", time: "3 hrs ago", status: "neutral" }];
const services = [{ name: "Server status", detail: "Cluster healthy · 12 nodes", status: "Operational", tone: "success", icon: FaServer }, { name: "Database status", detail: "Primary synced · 2.4 ms latency", status: "Healthy", tone: "success", icon: FaDatabase }, { name: "API status", detail: "99.99% uptime · 184 ms", status: "Operational", tone: "success", icon: FaCheckCircle }];

function SectionHeading({ title, description, action }) { return <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div>{action}</div>; }
export default function AdminDashboard({ onNavigate }) {
  return <div className="space-y-7 pb-6">
    <section className="relative overflow-hidden rounded-[2rem] bg-[#171b2c] px-6 py-7 text-white shadow-xl sm:px-8"><div className="absolute -right-14 -top-16 h-64 w-64 rounded-full bg-[#b32536]/30 blur-3xl" /><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-semibold"><FaShieldAlt /> Platform control centre</div><h1 className="mt-4 text-3xl font-bold tracking-tight">System Administrator</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Manage the UMULOPA platform, access controls, partner hospitals, security, and service reliability from one secure workspace.</p></div><div className="flex items-center gap-3 rounded-2xl border border-emerald-300/20 bg-emerald-400/10 px-4 py-3"><span className="h-2.5 w-2.5 rounded-full bg-emerald-400 shadow-[0_0_12px_#4ade80]" /><div><p className="text-sm font-semibold">Platform operational</p><p className="text-xs text-slate-300">Last checked just now</p></div></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(({ label, value, change, icon: Icon, tone }) => <article key={label} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-md"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div><span className={`grid h-11 w-11 place-items-center rounded-2xl ${tone}`}><Icon /></span></div><p className="mt-4 text-xs font-medium text-slate-500">{change}</p></article>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.55fr_.95fr]"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><SectionHeading title="Platform usage" description="Weekly authenticated activity across the UMULOPA network." action={<button onClick={() => onNavigate("/reports/usage")} className="text-sm font-semibold text-[#8f1220]">View analytics <FaArrowRight className="ml-1 inline" /></button>} /><div className="mt-6 h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={usage}><defs><linearGradient id="usageFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#a51d2d" stopOpacity=".32" /><stop offset="100%" stopColor="#a51d2d" stopOpacity="0" /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="day" tickLine={false} axisLine={false} /><YAxis tickLine={false} axisLine={false} /><Tooltip /><Area type="monotone" dataKey="users" name="Active users" stroke="#991b2b" strokeWidth={3} fill="url(#usageFill)" /></AreaChart></ResponsiveContainer></div></article>
      <article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><SectionHeading title="System notifications" description="Items that need your attention." /><div className="mt-5 space-y-3"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="flex items-center gap-2 text-sm font-bold text-amber-900"><FaBell /> 14 access approvals pending</p><p className="mt-1 text-xs text-amber-800">Review new staff and centre account requests.</p></div><div className="rounded-2xl border border-blue-100 bg-blue-50 p-4"><p className="text-sm font-bold text-blue-900">Backup completed successfully</p><p className="mt-1 text-xs text-blue-800">Encrypted nightly backup · 02:00 CAT</p></div><div className="rounded-2xl border border-rose-100 bg-rose-50 p-4"><p className="text-sm font-bold text-rose-900">Security review due</p><p className="mt-1 text-xs text-rose-800">Review administrator permissions this week.</p></div></div></article></section>
    <section className="grid gap-6 xl:grid-cols-[1.45fr_1fr]"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><SectionHeading title="User management" description="Recently added and recently updated accounts." action={<button onClick={() => onNavigate("/admin/users")} className="rounded-xl bg-[#8f1220] px-3 py-2 text-sm font-semibold text-white"><FaPlus className="mr-1 inline" /> Add user</button>} /><div className="mt-5 overflow-x-auto"><table className="min-w-full text-left"><thead className="border-b border-slate-100 text-xs uppercase tracking-wide text-slate-400"><tr><th className="pb-3">User</th><th className="pb-3">Role</th><th className="pb-3">Hospital</th><th className="pb-3">Status</th></tr></thead><tbody>{users.map((user) => <tr key={user.email} className="border-b border-slate-50 last:border-0"><td className="py-3"><p className="font-semibold text-slate-800">{user.name}</p><p className="text-xs text-slate-500">{user.email}</p></td><td className="py-3 text-sm text-slate-600">{user.role}</td><td className="py-3 text-sm text-slate-600">{user.hospital}</td><td className="py-3"><StatusBadge status={user.status === "Active" ? "success" : "warning"}>{user.status}</StatusBadge></td></tr>)}</tbody></table></div></article>
      <article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><SectionHeading title="Audit timeline" description="Latest platform-level actions." /><ol className="mt-5 space-y-4">{activity.map((item) => <li key={item.event} className="flex gap-3"><span className="mt-1 h-3 w-3 shrink-0 rounded-full bg-[#9d1b2b] ring-4 ring-rose-50" /><div><div className="flex gap-2"><p className="text-sm font-bold text-slate-800">{item.event}</p><span className="text-xs text-slate-400">{item.time}</span></div><p className="mt-1 text-xs leading-5 text-slate-500">{item.detail}</p></div></li>)}</ol></article></section>
    <section className="grid gap-6 xl:grid-cols-[.95fr_1.05fr]"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><SectionHeading title="Service health" description="Infrastructure and integration monitoring." /><div className="mt-5 space-y-3">{services.map(({ name, detail, status, tone, icon: Icon }) => <div key={name} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white text-[#8f1220] shadow-sm"><Icon /></span><div className="min-w-0 flex-1"><p className="font-semibold text-slate-800">{name}</p><p className="truncate text-xs text-slate-500">{detail}</p></div><StatusBadge status={tone}>{status}</StatusBadge></div>)}</div></article>
      <article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><SectionHeading title="Recent login activity" description="Successful authenticated sessions over the last 7 days." /><div className="mt-5 h-52"><ResponsiveContainer width="100%" height="100%"><BarChart data={usage}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="day" tickLine={false} axisLine={false} /><YAxis tickLine={false} axisLine={false} /><Tooltip /><Bar dataKey="requests" name="Logins" fill="#a51d2d" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></article></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><SectionHeading title="Quick actions" description="Every administrative control opens its working workflow." /><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[
      { label: "Manage Users", icon: FaUserPlus, path: "/admin/users" },
      { label: "Manage Hospitals", icon: FaHospital, path: "/admin/hospitals" },
      { label: "Approve Requests", icon: FaCheckCircle, path: "/regional/emergency" },
      { label: "Adjust Stock", icon: FaTint, path: "/regional/inventory" },
      { label: "View Reports", icon: FaFileAlt, path: "/admin/reports" },
      { label: "Run Backup", icon: FaDatabase, path: "/admin/backup" },
    ].map(({ label, icon: Icon, path }) => <button key={label} type="button" onClick={() => onNavigate(path)} className="flex min-h-16 items-center gap-3 rounded-2xl border border-slate-200 p-4 text-left transition hover:-translate-y-0.5 hover:border-[#a51d2d] hover:bg-rose-50 focus:outline-none focus:ring-4 focus:ring-[#a51d2d]/10"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#fff0f1] text-[#941625]"><Icon /></span><span className="font-semibold text-slate-800">{label}</span><FaArrowRight className="ml-auto text-slate-400" /></button>)}</div></section>
  </div>;
}
