import { FaArrowRight, FaCalendarCheck, FaCheckCircle, FaClock, FaHeart, FaTint, FaHospital, FaExclamationTriangle } from "react-icons/fa";
import { getDonorEligibility, getActualDonations } from "../../utils/donorEligibility";
import { uniqueRecords } from "../../utils/analytics";
import { useAppState } from "../../context/useAppState";
import { useNavigate } from "react-router-dom";

export default function DonorDashboard() {
  const navigate = useNavigate();
  const { user, donors = [], bloodRequests = [], donorAppointments = [], donorDonations = [], donorEmergencyRequests = [] } = useAppState();
  const donor = donors.find((d) => d.id === user?.donorId || d.email?.toLowerCase() === user?.email?.toLowerCase()) || donors.find((d) => d.email?.toLowerCase() === user?.email?.toLowerCase()) || null;
  const name = donor?.name || user?.name || user?.username || "Blood Donor";
  const bloodType = donor?.bloodType || "Not recorded";
  
  const hour = new Date().getHours();
  const timeGreeting = hour < 12 ? "Good morning" : hour < 17 ? "Good afternoon" : "Good evening";

  const myAppointments = donorAppointments.filter((a) => a.donorId === donor?.id || a.donor?.toLowerCase() === name.toLowerCase());
  const myDonations = uniqueRecords(donorDonations.filter((d) => d.donorId === donor?.id || d.donor?.toLowerCase() === name.toLowerCase()));
  const linkedEmergency = bloodRequests.filter((r) => ["High", "Critical", "Emergency"].includes(r.urgency) && !["Completed", "Delivered", "Fulfilled", "Cancelled"].includes(r.status) && r.bloodType === bloodType).map((r) => ({ id: `REQ-${r.id}`, bloodType: r.bloodType, hospitalName: r.hospitalName || "ZNBTS Copperbelt hospital", unitsRequired: r.units, message: `Urgent ${r.bloodType} blood requirement for ${r.patient}.`, requestId: r.id }));
  const emergency = [...linkedEmergency, ...donorEmergencyRequests.filter((r) => r.status === "Open" && (!r.bloodType || r.bloodType === bloodType))];
  const completedDonations = getActualDonations(myDonations).length;
  const eligibility = getDonorEligibility(myDonations);
  const nextAppointment = myAppointments.find((a) => ["Pending", "Confirmed"].includes(a.status));
  const cards = [
    ["Verified donations", completedDonations, "Recorded against your donor profile", FaHeart],
    ["Blood group", bloodType, "Your registered blood group", FaTint],
    ["Next appointment", nextAppointment?.date || "None", nextAppointment ? nextAppointment.status : "No appointment booked", FaCalendarCheck],
    ["Emergency calls", emergency.length, "Open requests matching your group", FaExclamationTriangle],
  ];
  return <div className="space-y-7 pb-8">
    <section className="rounded-[2rem] bg-gradient-to-r from-[#64101a] to-[#a9202f] px-6 py-7 text-white shadow-xl sm:px-8">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-semibold"><FaTint /> Zambia National Blood Transfusion Service (ZNBTS)</p><h1 className="mt-4 text-3xl font-bold">{timeGreeting}, {name}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/80">Your donor portal connects your availability, appointments and verified donations with the ZNBTS Copperbelt blood network.</p></div><div className="rounded-2xl border border-white/20 bg-white/10 px-4 py-3"><p className="text-sm font-semibold">Donor status</p><p className="mt-1 text-xs text-white/70">{donor?.status || "Active"} · {donor?.verified ? "Verified profile" : "Profile registered"}</p></div></div>
    </section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,note,Icon], index)=><article key={label} onClick={()=>navigate(["/donor/history","/donor/profile","/donor/appointments","/donor/emergency"][index])} role="button" tabIndex={0} onKeyDown={(e)=>e.key==="Enter"&&navigate(["/donor/history","/donor/profile","/donor/appointments","/donor/emergency"][index])} className="cursor-pointer rounded-3xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-[#a51d2d] hover:shadow-md"><div className="flex justify-between gap-3"><div><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div><span className="grid h-11 w-11 place-items-center rounded-2xl bg-rose-50 text-rose-700"><Icon/></span></div><p className="mt-4 text-xs font-medium text-slate-500">{note}</p></article>)}</section>
    {emergency.length > 0 && <section className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-amber-800">Urgent donor mobilisation</p><h2 className="mt-1 text-xl font-bold text-amber-950">ZNBTS needs {bloodType} donors</h2><p className="mt-1 text-sm text-amber-900">There {emergency.length === 1 ? "is" : "are"} {emergency.length} open emergency request{emergency.length === 1 ? "" : "s"} matching your blood group.</p></div><button onClick={()=>navigate("/donor/emergency")} className="rounded-xl bg-[#8f1220] px-5 py-3 text-sm font-bold text-white">View emergency request</button></div></section>}
    <section className="grid gap-6 lg:grid-cols-2">
      <article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm flex flex-col justify-between"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-slate-900">Donation readiness</h2><p className="mt-1 text-sm text-slate-500">Keep your donor profile and eligibility information current.</p></div><FaCheckCircle className="text-emerald-600"/></div><div className="mt-5 space-y-3"><div className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><span className="text-sm text-slate-600">Profile status</span><b className="text-sm">{donor ? "Registered" : "Incomplete"}</b></div><div className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><span className="text-sm text-slate-600">Blood group</span><b className="text-sm">{bloodType}</b></div><div className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><span className="text-sm text-slate-600">Last recorded donation</span><b className="text-sm">{eligibility.lastDonation?.date || "Not recorded"}</b></div><div className={`flex items-center justify-between rounded-2xl p-4 ${eligibility.eligible ? "bg-emerald-50 text-emerald-800" : "bg-amber-50 text-amber-800"}`}><span className="text-sm font-medium">Eligibility status</span><b className="text-sm font-bold">{eligibility.label}</b></div></div><button onClick={()=>navigate("/donor/eligibility")} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#8f1220] hover:underline">Check detailed eligibility <FaArrowRight/></button></article>
      <article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm flex flex-col justify-between"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-slate-900">Upcoming appointment</h2><p className="mt-1 text-sm text-slate-500">Manage your next visit with the selected ZNBTS centre.</p></div><FaCalendarCheck className="text-[#8f1220]"/></div>{nextAppointment?<div className="mt-5 rounded-2xl border border-slate-200 p-4"><div className="flex justify-between"><b>{nextAppointment.date}</b><span className="text-sm font-semibold text-[#8f1220]">{nextAppointment.status}</span></div><p className="mt-2 text-sm text-slate-600">{nextAppointment.centre || "ZNBTS Copperbelt donor centre"}</p></div>:<div className="mt-5 rounded-2xl border border-dashed border-slate-300 p-6 text-center"><FaClock className="mx-auto text-2xl text-slate-400"/><p className="mt-2 font-semibold text-slate-700">No appointment booked</p><p className="mt-1 text-sm text-slate-500">Choose a suitable date and submit a donation appointment request.</p></div>}<button onClick={()=>navigate("/donor/appointments")} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#8f1220] hover:underline">Manage appointments <FaArrowRight/></button></article>
    </section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900">Donor actions</h2><p className="mt-1 text-sm text-slate-500">Every action opens a working donor workflow.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Book donation",FaCalendarCheck,"/donor/donate"],["Donation history",FaHeart,"/donor/history"],["Emergency requests",FaExclamationTriangle,"/donor/emergency"],["Update profile",FaHospital,"/donor/profile"]].map(([label,Icon,path])=><button key={path} onClick={()=>navigate(path)} className="flex items-center gap-3 rounded-2xl border border-slate-200 p-4 text-left hover:border-[#a51d2d] hover:bg-rose-50"><span className="grid h-10 w-10 place-items-center rounded-xl bg-rose-50 text-[#941625]"><Icon/></span><span className="text-sm font-semibold text-slate-800">{label}</span><FaArrowRight className="ml-auto text-slate-400"/></button>)}</div></section>
  </div>;
}
