import { Bar, BarChart, CartesianGrid, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { FaAmbulance, FaArrowRight, FaBuilding, FaCheckCircle, FaExclamationTriangle, FaFileAlt, FaHospital, FaTint, FaTruck, FaUsers } from "react-icons/fa";
import StatusBadge from "../../components/StatusBadge";
import { useAppState } from "../../context/useAppState";
import { operationalSummary } from "../../utils/analytics";
import { aggregateByGroup, facilityTotals } from "../../utils/networkInventory";

function Heading({ title, text, action }) { return <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{text}</p></div>{action}</div>; }
export default function RegionalDashboard({ onNavigate }) {
  const { patients=[], bloodRequests=[], transfusions=[], donors=[], networkInventory=[], hospitals=[], transfers=[], user } = useAppState();
  const networkGroups = aggregateByGroup(networkInventory).map((x) => ({ type: x.bloodGroup, quantity: x.available, threshold: x.bloodGroup.includes("-") ? 5 : 10 }));
  const s = operationalSummary({ patients, bloodRequests, transfusions, donors, stock: networkGroups, hospitals, transfers });
  const metrics = [["Total blood units",s.stock.totalUnits,"Current regional stock",FaTint], ["Connected hospitals",s.hospitals.length,"Registered facilities",FaHospital], ["Active transfers",s.activeTransfers,"Not completed or cancelled",FaTruck], ["Emergency requests",s.requests.critical,"Require immediate action",FaAmbulance], ["Low stock groups",s.stock.lowStock,"Below configured thresholds",FaExclamationTriangle], ["Registered donors",s.donors.length,"Unique donor records",FaUsers]];
  const bloodMix = s.stock.byGroup;
  const facilityRows = facilityTotals(networkInventory);
  const hospitalRows = s.hospitals.map((h) => ({ ...h, units: Number(facilityRows.find((f) => f.facilityId === `HOSP-${h.id}`)?.available ?? 0) }));

  const hour = new Date().getHours();
  const timeGreeting = hour < 12 ? "Good morning" : hour < 17 ? "Good afternoon" : "Good evening";
  const userName = user?.name || user?.username || "Regional Officer";

  return <div className="space-y-7 pb-6">
    <section className="relative overflow-hidden rounded-[2rem] bg-gradient-to-r from-[#690f1b] via-[#941725] to-[#b52a36] px-6 py-7 text-white shadow-xl sm:px-8"><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-semibold"><FaBuilding /> ZNBTS Copperbelt Regional Coordination</p><h1 className="mt-4 text-3xl font-bold">{timeGreeting}, {userName}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/80">Coordinate blood availability, hospital requests, emergency escalation and inter-hospital transfers across the Copperbelt.</p></div><div className="rounded-2xl border border-white/20 bg-white/10 px-4 py-3"><p className="text-sm font-semibold">Operational analytics</p><p className="mt-1 text-xs text-white/70">Derived from current application records.</p></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{metrics.map(([label,value,note,Icon], index)=><article key={label} onClick={()=>onNavigate(["/regional/inventory","/regional/hospitals","/regional/transfers","/regional/emergency","/regional/inventory","/donors"][index])} role="button" tabIndex={0} onKeyDown={(e)=>e.key==="Enter"&&onNavigate(["/regional/inventory","/regional/hospitals","/regional/transfers","/regional/emergency","/regional/inventory","/donors"][index])} className="cursor-pointer rounded-3xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-[#a51d2d] hover:shadow-md"><div className="flex justify-between gap-3"><div><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div><span className="grid h-11 w-11 place-items-center rounded-2xl bg-rose-50 text-rose-700"><Icon /></span></div><p className="mt-4 text-xs font-medium text-slate-500">{note}</p></article>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.4fr_.9fr]"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Heading title="Regional blood inventory" text="Actual available units by blood group." action={<button onClick={()=>onNavigate("/regional/inventory")} className="text-sm font-semibold text-[#8f1220]">View all inventory <FaArrowRight className="inline"/></button>}/><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={bloodMix.length ? bloodMix : [{name:"No stock",value:0}]}><CartesianGrid vertical={false} stroke="#e2e8f0"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="value" name="Units" fill="#9d1b2b" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></article><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Heading title="Blood mix" text="Share of current stock; percentages are calculated from the same total."/><div className="mt-4 h-52"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={bloodMix.length?bloodMix:[{name:"No stock",value:1}]} dataKey="value" nameKey="name" innerRadius={52} outerRadius={78} paddingAngle={3} fill="#9d1b2b"/><Tooltip/></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-2 text-xs text-slate-600">{bloodMix.map(x=><span key={x.name} className="rounded-lg bg-slate-50 px-2 py-1">{x.name}: <b>{s.stock.totalUnits ? Math.round((x.value/s.stock.totalUnits)*100) : 0}%</b></span>)}</div></article></section>
    <section className="grid gap-6 xl:grid-cols-[1.3fr_1fr]"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Heading title="Hospital network" text="Registered hospitals and their reported stock." action={<button onClick={()=>onNavigate("/regional/hospitals")} className="text-sm font-semibold text-[#8f1220]">View all hospitals</button>}/><div className="mt-5 overflow-x-auto"><table className="min-w-full text-left"><thead className="border-b border-slate-100 text-xs uppercase tracking-wide text-slate-400"><tr><th className="pb-3">Hospital</th><th className="pb-3">Units</th><th className="pb-3">Status</th></tr></thead><tbody>{hospitalRows.map(h=><tr key={h.id} className="border-b border-slate-50"><td className="py-3 font-semibold text-slate-800">{h.name}</td><td className="py-3 text-sm">{h.units}</td><td className="py-3"><StatusBadge status={h.status === "Active" || h.status === "Stable" ? "success" : "warning"}>{h.status || "Active"}</StatusBadge></td></tr>)}</tbody></table>{!hospitalRows.length&&<p className="py-8 text-center text-sm text-slate-500">No hospitals registered yet.</p>}</div></article><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Heading title="Escalation queue" text="Emergency requests awaiting regional action." action={<button onClick={()=>onNavigate("/regional/emergency")} className="text-sm font-semibold text-[#8f1220]">View all</button>}/><div className="mt-5 space-y-3">{s.requests.unique.filter(r=>r.status==="Escalated"||["High","Critical","Emergency"].includes(r.urgency)).slice(0,5).map(r=><div key={r.id} className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex justify-between gap-3"><p className="font-bold text-amber-900">{r.patient}</p><StatusBadge status="warning">{r.status}</StatusBadge></div><p className="mt-1 text-sm text-amber-800">{r.bloodType} · {r.units} units · {r.urgency}</p></div>)}{!s.requests.unique.filter(r=>r.status==="Escalated"||["High","Critical","Emergency"].includes(r.urgency)).length&&<p className="text-sm text-slate-500">No emergency escalations currently waiting.</p>}</div></article></section>
    <section className="grid gap-6 xl:grid-cols-2"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Heading title="Transfers" text="Current transfer workflow state." action={<button onClick={()=>onNavigate("/regional/transfers")} className="text-sm font-semibold text-[#8f1220]">View all transfers</button>}/><div className="mt-5 space-y-3">{s.transfers.slice(0,5).map(t=><div key={t.id} className="flex justify-between rounded-2xl bg-slate-50 p-4"><span><b>{t.hospital}</b><p className="text-xs text-slate-500">{t.blood} · {t.units} units</p></span><StatusBadge status={t.status==="Completed"?"success":"info"}>{t.status}</StatusBadge></div>)}{!s.transfers.length&&<p className="text-sm text-slate-500">No transfers recorded.</p>}</div></article><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Heading title="Quick actions" text="Open the corresponding operational workflow."/><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["Allocate Blood",FaTint,"/regional/distribution"],["Dispatch Transfer",FaTruck,"/regional/transfers"],["Emergency Requests",FaAmbulance,"/regional/emergency"],["Regional Reports",FaFileAlt,"/regional/reports"],["Hospital Network",FaHospital,"/regional/hospitals"],["Analytics",FaCheckCircle,"/regional/analytics"]].map(([label,Icon,path])=><button key={label} onClick={()=>onNavigate(path)} className="flex items-center gap-3 rounded-2xl border border-slate-200 p-4 text-left hover:border-[#a51d2d] hover:bg-rose-50"><span className="grid h-10 w-10 place-items-center rounded-xl bg-rose-50 text-[#941625]"><Icon/></span><span className="text-sm font-semibold text-slate-800">{label}</span><FaArrowRight className="ml-auto text-slate-400"/></button>)}</div></article></section>
  </div>;
}
