import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { FaArrowRight, FaClipboardList, FaHeartbeat, FaHospital, FaSearch, FaTint, FaUserPlus, FaUsers, FaAmbulance } from "react-icons/fa";
import StatusBadge from "../../components/StatusBadge";
import { useAppState } from "../../context/useAppState";
import { operationalSummary } from "../../utils/analytics";
import { getFacilityInventory } from "../../utils/networkInventory";
import { canAccessRoute } from "../../utils/roles";
import { scopeToHospital } from "../../utils/hospitalScope";

function Heading({ title, text, action }) { return <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{text}</p></div>{action}</div>; }

export default function StaffDashboard({ onNavigate }) {
  const { patients = [], bloodRequests = [], transfusions = [], donors = [], networkInventory = [], user } = useAppState();
  const hospitalId = user?.hospitalId;
  const scopedPatients = scopeToHospital(patients, user);
  const scopedRequests = scopeToHospital(bloodRequests, user);
  const scopedTransfusions = scopeToHospital(transfusions, user);
  const scopedDonors = hospitalId ? donors.filter((d) => String(d.nearestHospitalId ?? "") === String(hospitalId)) : donors;
  const ownInventory = hospitalId ? getFacilityInventory(networkInventory, `HOSP-${hospitalId}`).map((r) => ({ ...r, type: r.bloodGroup, quantity: r.available, threshold: r.threshold })) : [];
  const summary = operationalSummary({ patients: scopedPatients, bloodRequests: scopedRequests, transfusions: scopedTransfusions, donors: scopedDonors, stock: ownInventory });
  const hospitalName = user?.hospital && user.hospital !== "—" ? user.hospital : "Registered Hospital";
  const inventory = summary.stock.byGroup.length ? summary.stock.byGroup : [{ name: "No stock", value: 0 }];
  const recentPatients = summary.patients.unique.slice(-5).reverse();
  const recentTransfusions = summary.transfusions.slice(-5).reverse();
  const cards = [
    ["Registered patients", summary.patients.total, "Actual unique patient records", FaUsers],
    ["Blood requests", summary.requests.total, `${summary.requests.pending} awaiting action`, FaClipboardList],
    ["Transfusions", summary.totalTransfusions, "Recorded transfusion events", FaHeartbeat],
    ["Blood units available", summary.stock.totalUnits, `${summary.stock.byGroup.length} blood groups in stock`, FaTint],
    ["Critical requests", summary.requests.critical, "Require immediate review", FaAmbulance],
  ];
  const hour = new Date().getHours();
  const timeGreeting = hour < 12 ? "Good morning" : hour < 17 ? "Good afternoon" : "Good evening";
  const userName = user?.name || user?.username || user?.email?.split("@")[0] || "Hospital Officer";

  return <div className="space-y-7 pb-6">
    <section className="relative overflow-hidden rounded-[2rem] bg-gradient-to-r from-[#64101a] to-[#a9202f] px-6 py-7 text-white shadow-xl sm:px-8">
      <div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-semibold"><FaHospital /> Hospital Staff Dashboard</p><h1 className="mt-4 text-3xl font-bold">{timeGreeting}, {userName}</h1><p className="mt-1 text-sm text-white/90 font-medium">{hospitalName} · {user?.subRole || "Staff Account"}</p><p className="mt-2 max-w-2xl text-sm leading-6 text-white/80">Manage patient registration, blood requests, transfusions and hospital blood-stock workflows.</p></div><div className="rounded-2xl border border-white/20 bg-white/10 px-4 py-3"><p className="text-sm font-semibold">Live application state</p><p className="mt-1 text-xs text-white/70">All figures below are derived from current records.</p></div></div>
    </section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label, value, note, Icon], index) => <article key={label} onClick={() => onNavigate(["/patients", "/patients/request", "/patients/transfusions", "/inventory", "/staff/emergency"][index])} role="button" tabIndex={0} onKeyDown={(e)=>e.key==="Enter"&&onNavigate(["/patients", "/patients/request", "/patients/transfusions", "/inventory", "/staff/emergency"][index])} className="cursor-pointer rounded-3xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-[#a51d2d] hover:shadow-md"><div className="flex justify-between"><div><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div><span className="grid h-11 w-11 place-items-center rounded-2xl bg-rose-50 text-rose-700"><Icon /></span></div><p className="mt-4 text-xs font-medium text-slate-500">{note}</p></article>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.3fr_.95fr]"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Heading title="Blood inventory" text="Current available units by blood group." action={<button onClick={() => onNavigate("/inventory")} className="text-sm font-semibold text-[#8f1220]">Open inventory <FaArrowRight className="inline" /></button>} /><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={inventory}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="name" axisLine={false} tickLine={false} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} /><Tooltip /><Bar dataKey="value" name="Units" fill="#9d1b2b" radius={[6,6,0,0]} /></BarChart></ResponsiveContainer></div></article><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Heading title="Stock alerts" text="Calculated from configured safety thresholds." /><div className="mt-5 space-y-3">{summary.stock.unique.filter((s) => Number(s.quantity ?? s.units) <= Number(s.threshold)).slice(0, 5).map((s) => <div key={s.id} className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="font-bold text-amber-900">{s.type} · {s.quantity ?? s.units} units remaining</p><p className="mt-1 text-sm text-amber-800">Safety threshold: {s.threshold} units.</p></div>)}{summary.stock.lowStock === 0 && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">All configured blood groups are above their safety thresholds.</div>}</div></article></section>
    <section className="grid gap-6 xl:grid-cols-[1.35fr_.95fr]"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Heading title="Recent patients" text="Latest unique registrations." action={<button onClick={() => onNavigate("/patients")} className="text-sm font-semibold text-[#8f1220]">View all <FaArrowRight className="inline" /></button>} /><div className="mt-5 overflow-x-auto"><table className="min-w-full text-left"><thead className="border-b border-slate-100 text-xs uppercase tracking-wide text-slate-400"><tr><th className="pb-3">Patient</th><th className="pb-3">Blood group</th><th className="pb-3">Ward</th><th className="pb-3">Status</th></tr></thead><tbody>{recentPatients.map((patient) => <tr key={patient.id} className="border-b border-slate-50"><td className="py-3"><p className="text-sm font-semibold text-slate-800">{patient.name || `${patient.firstName || ""} ${patient.lastName || ""}`.trim()}</p><p className="text-xs text-slate-500">{patient.patientId || `Record ${patient.id}`}</p></td><td className="py-3 text-sm text-slate-600">{patient.bloodGroup || patient.bloodType || "—"}</td><td className="py-3 text-sm text-slate-600">{patient.ward || "Not assigned"}</td><td className="py-3"><StatusBadge status="info">Active</StatusBadge></td></tr>)}</tbody></table>{!recentPatients.length && <p className="py-8 text-center text-sm text-slate-500">No patient records yet.</p>}</div></article><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Heading title="Request summary" text="Counts are mutually derived from the same request set." /><div className="mt-5 space-y-3"><div className="flex justify-between rounded-2xl bg-slate-50 p-4"><span>Pending / escalated</span><b>{summary.requests.pending}</b></div><div className="flex justify-between rounded-2xl bg-slate-50 p-4"><span>Approved</span><b>{summary.requests.approved}</b></div><div className="flex justify-between rounded-2xl bg-slate-50 p-4"><span>Completed</span><b>{summary.requests.completed}</b></div><div className="flex justify-between rounded-2xl bg-red-50 p-4 text-red-800"><span>Critical</span><b>{summary.requests.critical}</b></div><div className="flex justify-between rounded-2xl border border-slate-200 p-4"><span>Total units requested</span><b>{summary.requests.unitsRequested}</b></div></div></article></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Heading title="Recent transfusions" text="Recorded transfusion events from application state." action={<button onClick={() => onNavigate("/patients/transfusions")} className="text-sm font-semibold text-[#8f1220]">View all</button>} /><div className="mt-5 grid gap-3 md:grid-cols-2">{recentTransfusions.map((item) => <div key={item.id} className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><div><p className="font-semibold text-slate-800">{item.patient}</p><p className="text-xs text-slate-500">{item.bloodType || item.blood} · {item.units} units · {item.date || item.time || "No date"}</p></div><StatusBadge status={item.outcome === "Successful" || item.status === "Completed" ? "success" : "info"}>{item.outcome || item.status || "Recorded"}</StatusBadge></div>)}{!recentTransfusions.length && <p className="text-sm text-slate-500">No transfusion records yet.</p>}</div></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Heading title="Quick actions" text="Role-authorized operational actions." /><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Register Patient",FaUserPlus,"/patients/add"],["Create Blood Request",FaClipboardList,"/patients/request"],["Hospital Blood Bank",FaTint,"/staff/blood-bank"],["Issue / Record Blood Use",FaHeartbeat,"/patients/transfusions"],["Search Patient",FaSearch,"/patients"],["ZNBTS Network Stock",FaTint,"/network/inventory"]].filter(([,,path]) => canAccessRoute(user?.role, path, user?.subRole)).map(([label,Icon,path]) => <button key={label} onClick={() => onNavigate(path)} className="flex items-center gap-3 rounded-2xl border border-slate-200 p-4 text-left hover:border-[#a51d2d] hover:bg-rose-50"><span className="grid h-10 w-10 place-items-center rounded-xl bg-rose-50 text-[#941625]"><Icon /></span><span className="text-sm font-semibold text-slate-800">{label}</span><FaArrowRight className="ml-auto text-slate-400" /></button>)}</div></section>
  </div>;
}
