import { BLOOD_GROUPS } from "./analytics.js";

export const ZNBTS_FACILITY_ID = "ZNBTS-CB-KITWE-KTH";
export const ZNBTS_FACILITY_NAME = "ZNBTS Kitwe Blood Centre";
export const ZNBTS_PARENT_HOSPITAL_ID = 2;
export const INVENTORY_STATES = Object.freeze({ PENDING_TESTING: "Pending ZNBTS Testing", TESTING: "Testing", AVAILABLE: "Available", RESERVED: "Reserved", ISSUED: "Issued", EXPIRED: "Expired", DISCARDED: "Discarded" });
const n = (v) => Number.isFinite(Number(v)) ? Number(v) : 0;
export const inventoryKey = (facilityId, bloodGroup) => `${facilityId}::${bloodGroup}`;
export function normaliseInventoryRows(rows = []) { return rows.map(r => ({ id:r.id||inventoryKey(r.facilityId,r.bloodGroup), facilityId:r.facilityId, facilityName:r.facilityName, facilityType:r.facilityType||"Hospital", province:r.province||"Copperbelt", district:r.district||"", bloodGroup:r.bloodGroup, available:n(r.available), testing:n(r.testing), pendingTesting:n(r.pendingTesting), reserved:n(r.reserved), issued:n(r.issued), expired:n(r.expired), discarded:n(r.discarded), threshold:n(r.threshold||5), updatedAt:r.updatedAt||new Date().toISOString() })); }
export function seedNetworkInventory(hospitals=[]) { const base=[["A+",24],["A-",6],["B+",19],["B-",5],["AB+",8],["AB-",3],["O+",31],["O-",7]]; const rows=[]; base.forEach(([bloodGroup,available])=>rows.push({facilityId:ZNBTS_FACILITY_ID,facilityName:ZNBTS_FACILITY_NAME,facilityType:"ZNBTS",province:"Copperbelt",district:"Kitwe",parentHospitalId:ZNBTS_PARENT_HOSPITAL_ID,bloodGroup,available,testing:2,pendingTesting:0,reserved:1,issued:0,expired:0,discarded:0,threshold:bloodGroup.includes("-")?5:10,updatedAt:new Date().toISOString()})); hospitals.forEach((h,i)=>{const a=i===0?[["A+",8],["O+",10],["O-",2],["B+",6]]:i===1?[["A+",6],["B+",5],["O+",8],["O-",1]]:i===2?[["A+",3],["B+",4],["O+",5],["A-",1]]:[["A+",4],["B+",3],["O+",6],["O-",1]]; a.forEach(([bloodGroup,available])=>rows.push({facilityId:`HOSP-${h.id}`,facilityName:h.name,facilityType:"Hospital",province:h.province||"Copperbelt",district:h.district||"",bloodGroup,available,testing:0,pendingTesting:0,reserved:0,issued:0,expired:0,discarded:0,threshold:bloodGroup.includes("-")?3:5,updatedAt:new Date().toISOString()}));}); return normaliseInventoryRows(rows); }
export function aggregateByGroup(rows=[]) { return BLOOD_GROUPS.map(bloodGroup=>{const m=rows.filter(r=>r.bloodGroup===bloodGroup);return {bloodGroup,available:m.reduce((s,r)=>s+n(r.available),0),testing:m.reduce((s,r)=>s+n(r.testing),0),pendingTesting:m.reduce((s,r)=>s+n(r.pendingTesting),0),reserved:m.reduce((s,r)=>s+n(r.reserved),0),issued:m.reduce((s,r)=>s+n(r.issued),0),expired:m.reduce((s,r)=>s+n(r.expired),0),discarded:m.reduce((s,r)=>s+n(r.discarded),0),facilities:m.filter(r=>r.available>0).length};}); }
export function facilityTotals(rows=[]) { const map=new Map(); rows.forEach(r=>{const x=map.get(r.facilityId)||{facilityId:r.facilityId,facilityName:r.facilityName,facilityType:r.facilityType,province:r.province,district:r.district,available:0,testing:0,pendingTesting:0,reserved:0,issued:0,expired:0,discarded:0,groups:0,updatedAt:r.updatedAt}; x.available+=n(r.available);x.testing+=n(r.testing);x.pendingTesting+=n(r.pendingTesting);x.reserved+=n(r.reserved);x.issued+=n(r.issued);x.expired+=n(r.expired);x.discarded+=n(r.discarded);x.groups+=r.available>0?1:0;x.updatedAt=r.updatedAt>x.updatedAt?r.updatedAt:x.updatedAt;map.set(r.facilityId,x);}); return [...map.values()]; }
export function getFacilityInventory(rows=[],facilityId) { return BLOOD_GROUPS.map(b=>rows.find(r=>r.facilityId===facilityId&&r.bloodGroup===b)||({facilityId,bloodGroup:b,available:0,testing:0,pendingTesting:0,reserved:0,issued:0,expired:0,discarded:0,threshold:b.includes("-")?3:5})); }
export function applyInventoryChange(rows, change) { const now=new Date().toISOString(); const key=inventoryKey(change.facilityId,change.bloodGroup); const i=rows.findIndex(r=>inventoryKey(r.facilityId,r.bloodGroup)===key); const current=i>=0?rows[i]:{id:key,facilityId:change.facilityId,facilityName:change.facilityName,facilityType:change.facilityType||"Hospital",province:change.province||"Copperbelt",district:change.district||"",bloodGroup:change.bloodGroup,available:0,testing:0,pendingTesting:0,reserved:0,issued:0,expired:0,discarded:0,threshold:change.bloodGroup.includes("-")?3:5,updatedAt:now}; const next={...current,available:current.available+n(change.deltaAvailable),testing:current.testing+n(change.deltaTesting),pendingTesting:current.pendingTesting+n(change.deltaPendingTesting),reserved:current.reserved+n(change.deltaReserved),issued:current.issued+n(change.deltaIssued),expired:current.expired+n(change.deltaExpired),discarded:current.discarded+n(change.deltaDiscarded),updatedAt:now}; if(next.available<0||next.testing<0||next.pendingTesting<0||next.reserved<0||next.issued<0||next.expired<0||next.discarded<0) throw new Error("Inventory cannot become negative."); const nextRows=[...rows]; if(i>=0)nextRows[i]=next;else nextRows.push(next); return {rows:nextRows,transaction:{id:`TX-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,facilityId:change.facilityId,facilityName:next.facilityName,bloodGroup:change.bloodGroup,quantity:Math.abs(n(change.quantity||change.deltaAvailable||change.deltaTesting||change.deltaPendingTesting||change.deltaReserved)),transactionType:change.transactionType,referenceId:change.referenceId||null,performedBy:change.performedBy||null,timestamp:now}}; }
