import { useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useAppState } from '../../context/useAppState';
import { applyInventoryChange, getFacilityInventory, INVENTORY_STATES, ZNBTS_FACILITY_ID, ZNBTS_FACILITY_NAME } from '../../utils/networkInventory';
import { ROLES, normaliseRole } from '../../utils/roles';
import { hasCapability } from '../../utils/hospitalCapabilities';
import { createReference, makeLot, consumeLots } from '../../utils/bloodInventory';

const GROUPS=['A+','A-','B+','B-','AB+','AB-','O+','O-'];
const input='w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-[#8f1220] focus:bg-white';
const today=()=>new Date().toISOString().slice(0,10);

export default function AddBloodPack(){
 const navigate=useNavigate(); const location=useLocation();
 const {user,hospitals=[],networkInventory,setNetworkInventory,inventoryLots=[],setInventoryLots,setInventoryTransactions,setAuditLogs}=useAppState();
 const role=normaliseRole(user?.role); const regional=role===ROLES.REGIONAL_CENTRE; const admin=role===ROLES.ADMIN; const hospitalUser=role===ROLES.HOSPITAL_STAFF;
 const params=new URLSearchParams(location.search); const requested=params.get('action');
 const mode=requested || (hospitalUser?'collect':'receive-external');
 const hospital=hospitalUser?hospitals.find(h=>Number(h.id)===Number(user?.hospitalId)):null;
 const [form,setForm]=useState({bloodGroup:'',units:'',collectionDate:today(),expiryDate:'',collectionReference:'',unitIdentifiers:'',sourceFacilityId:params.get('lot')||'',sourceFacilityName:'',receivingDate:today(),storageLocation:'Kitwe Blood Centre - Main Blood Bank',testingReference:'',testResult:'',reason:'',adjustment:1});
 const [msg,setMsg]=useState(''); const [error,setError]=useState('');
 const znbts={facilityId:ZNBTS_FACILITY_ID,facilityName:ZNBTS_FACILITY_NAME,facilityType:'ZNBTS',district:'Kitwe'};
 const sourceOptions=hospitals.filter(h=>h.status==='Active');
 const pendingLots=inventoryLots.filter(l=>l.status===INVENTORY_STATES.PENDING_TESTING && l.remaining>0);
 const testingLots=inventoryLots.filter(l=>l.facilityId===ZNBTS_FACILITY_ID && l.status===INVENTORY_STATES.TESTING && l.remaining>0);
 const clear=()=>{setMsg('');setError('');};
 const update=e=>setForm(v=>({...v,[e.target.name]:e.target.value}));
 const requireCommon=()=>{const units=Number(form.units); if(!GROUPS.includes(form.bloodGroup)) throw new Error('Select a valid blood group.'); if(!Number.isInteger(units)||units<1) throw new Error('Units must be a positive whole number.'); if(!form.collectionDate) throw new Error('Collection date is required.'); if(form.expiryDate && form.expiryDate<=form.collectionDate) throw new Error('Expiry date must be after collection date.'); return units;};
 const recordCollection=e=>{e.preventDefault();clear();try{if(!hospital)throw new Error('Hospital account required.'); if(!hasCapability(hospital,'collection'))throw new Error('This hospital is not authorized by ZNBTS for blood collection.'); if(!hasCapability(hospital,'storage'))throw new Error('This hospital is not authorized by ZNBTS for blood storage.'); const units=requireCommon(); const status=hasCapability(hospital,'testing')?INVENTORY_STATES.TESTING:INVENTORY_STATES.PENDING_TESTING; const facilityId=`HOSP-${hospital.id}`; const lot=makeLot({facilityId,facilityName:hospital.name,bloodGroup:form.bloodGroup,units,collectionDate:form.collectionDate,expiryDate:form.expiryDate, status, source:'Hospital collection',collectionReference:form.collectionReference||createReference('COL'),unitIdentifiers:form.unitIdentifiers.split(/[,\n ]+/).filter(Boolean),storageLocation:form.storageLocation||'Hospital Blood Bank',testingAuthority:hasCapability(hospital,'testing')?hospital.name:ZNBTS_FACILITY_NAME,metadata:{receivedAt:new Date().toISOString(),receivedBy:user.email}}); const r=applyInventoryChange(networkInventory,{...lot,quantity:units,deltaPendingTesting:status===INVENTORY_STATES.PENDING_TESTING?units:0,deltaTesting:status===INVENTORY_STATES.TESTING?units:0,transactionType:status===INVENTORY_STATES.TESTING?'DONATION_COLLECTED_FOR_AUTHORIZED_TESTING':'DONATION_COLLECTED_AWAITING_ZNBTS_TESTING',referenceId:lot.collectionReference,performedBy:user.email}); setNetworkInventory(r.rows);setInventoryLots(v=>[lot,...v]);setInventoryTransactions(v=>[r.transaction,...v]);setAuditLogs(v=>[{id:createReference('AUD'),event:'Blood collection recorded',detail:`${units} ${lot.bloodGroup} unit(s) collected at ${hospital.name} · ${status}`,time:new Date().toLocaleString()},...v]);setMsg(`${units} ${lot.bloodGroup} unit(s) recorded. ${status===INVENTORY_STATES.PENDING_TESTING?'Awaiting ZNBTS testing.':'In authorized testing.'}`);setForm(v=>({...v,bloodGroup:'',units:'',collectionReference:'',unitIdentifiers:''}));}catch(err){setError(err.message)}};
 const receiveForTesting=e=>{e.preventDefault();clear();try{if(!regional&&!admin)throw new Error('Only ZNBTS users can receive blood for testing.'); const lot=inventoryLots.find(l=>l.id===form.sourceFacilityId); if(!lot||lot.status!==INVENTORY_STATES.PENDING_TESTING)throw new Error('Select a pending collection lot.'); if(Number(lot.remaining)<1)throw new Error('Selected lot has no remaining units.'); const qty=Number(lot.remaining); let rows=networkInventory; const out=applyInventoryChange(rows,{facilityId:lot.facilityId,facilityName:lot.facilityName,facilityType:'Hospital',province:'Copperbelt',district:lot.district,bloodGroup:lot.bloodGroup,quantity:qty,deltaPendingTesting:-qty,transactionType:'TRANSFER_TO_ZNBTS_TESTING',referenceId:lot.id,performedBy:user.email}); rows=out.rows; const inn=applyInventoryChange(rows,{...znbts,bloodGroup:lot.bloodGroup,quantity:qty,deltaTesting:qty,transactionType:'RECEIVED_FOR_ZNBTS_TESTING',referenceId:lot.id,performedBy:user.email}); rows=inn.rows; const next={...lot,facilityId:ZNBTS_FACILITY_ID,facilityName:ZNBTS_FACILITY_NAME,facilityType:'ZNBTS',status:INVENTORY_STATES.TESTING,sourceFacilityId:lot.facilityId,sourceFacilityName:lot.facilityName,receivedAt:form.receivingDate+'T00:00:00',receivedBy:user.email,testingAuthority:ZNBTS_FACILITY_NAME,storageLocation:form.storageLocation,updatedAt:new Date().toISOString()}; setNetworkInventory(rows);setInventoryLots(v=>v.map(x=>x.id===lot.id?next:x));setInventoryTransactions(v=>[inn.transaction,out.transaction,...v]);setAuditLogs(v=>[{id:createReference('AUD'),event:'Blood received for ZNBTS testing',detail:`${qty} ${lot.bloodGroup} unit(s) received from ${lot.facilityName}`,time:new Date().toLocaleString()},...v]);setMsg(`${qty} ${lot.bloodGroup} unit(s) received into ZNBTS testing.`);}catch(err){setError(err.message)}};
 const externalReceive=e=>{e.preventDefault();clear();try{if(!regional&&!admin)throw new Error('Only ZNBTS users can receive external blood.'); const units=requireCommon(); if(!form.sourceFacilityName)throw new Error('Source facility is required.'); if(!form.testingReference)throw new Error('Testing/reference number is required for intake.'); const lot=makeLot({...znbts,bloodGroup:form.bloodGroup,units,collectionDate:form.collectionDate,expiryDate:form.expiryDate,status:INVENTORY_STATES.TESTING,source:'External blood intake',collectionReference:form.collectionReference||createReference('INTAKE'),unitIdentifiers:form.unitIdentifiers.split(/[,\n ]+/).filter(Boolean),storageLocation:form.storageLocation,testingAuthority:ZNBTS_FACILITY_NAME,sourceFacilityId:form.sourceFacilityId||null,sourceFacilityName:form.sourceFacilityName,metadata:{receivedAt:form.receivingDate+'T00:00:00',receivedBy:user.email,testingReference:form.testingReference,testingStatus:'Pending'}}); const r=applyInventoryChange(networkInventory,{...znbts,bloodGroup:form.bloodGroup,quantity:units,deltaTesting:units,transactionType:'EXTERNAL_BLOOD_RECEIVED_FOR_TESTING',referenceId:lot.collectionReference,performedBy:user.email});setNetworkInventory(r.rows);setInventoryLots(v=>[lot,...v]);setInventoryTransactions(v=>[r.transaction,...v]);setAuditLogs(v=>[{id:createReference('AUD'),event:'External blood intake received',detail:`${units} ${form.bloodGroup} unit(s) received from ${form.sourceFacilityName} for testing`,time:new Date().toLocaleString()},...v]);setMsg(`${units} ${form.bloodGroup} unit(s) received into ZNBTS testing. They are not available until released.`);}catch(err){setError(err.message)}};
 const releaseTesting=e=>{e.preventDefault();clear();try{if(!regional&&!admin)throw new Error('Only ZNBTS users can release central blood.'); const lot=inventoryLots.find(l=>l.id===form.sourceFacilityId); if(!lot||lot.facilityId!==ZNBTS_FACILITY_ID||lot.status!==INVENTORY_STATES.TESTING)throw new Error('Select a ZNBTS testing lot.'); const qty=Number(lot.remaining);if(qty<1)throw new Error('Lot has no remaining units.');if(!form.testingReference||!form.testResult)throw new Error('Testing reference and result are required.'); if(form.testResult==='FAIL'){if(!form.reason)throw new Error('Failure/disposition reason is required.'); const r=applyInventoryChange(networkInventory,{...znbts,bloodGroup:lot.bloodGroup,quantity:qty,deltaTesting:-qty,deltaDiscarded:qty,transactionType:'ZNBTS_TESTING_FAILED',referenceId:lot.id,performedBy:user.email}); const next={...lot,remaining:0,status:INVENTORY_STATES.DISCARDED,testingStatus:'Failed',testingReference:form.testingReference,testResult:'FAIL',dispositionReason:form.reason,updatedAt:new Date().toISOString()};setNetworkInventory(r.rows);setInventoryLots(v=>v.map(x=>x.id===lot.id?next:x));setInventoryTransactions(v=>[r.transaction,...v]);setAuditLogs(v=>[{id:createReference('AUD'),event:'ZNBTS testing failed',detail:`${qty} ${lot.bloodGroup} unit(s) failed testing · ${form.reason}`,time:new Date().toLocaleString()},...v]);setMsg(`${qty} ${lot.bloodGroup} unit(s) were rejected and discarded after a FAIL result.`);return;} const r=applyInventoryChange(networkInventory,{...znbts,bloodGroup:lot.bloodGroup,quantity:qty,deltaTesting:-qty,deltaAvailable:qty,transactionType:'ZNBTS_TESTING_RELEASED',referenceId:lot.id,performedBy:user.email}); const next={...lot,status:INVENTORY_STATES.AVAILABLE,testingStatus:'Released',testingReference:form.testingReference,testResult:form.testResult,releaseReference:createReference('REL'),updatedAt:new Date().toISOString()};setNetworkInventory(r.rows);setInventoryLots(v=>v.map(x=>x.id===lot.id?next:x));setInventoryTransactions(v=>[r.transaction,...v]);setAuditLogs(v=>[{id:createReference('AUD'),event:'ZNBTS blood released',detail:`${qty} ${lot.bloodGroup} unit(s) released to available stock after PASS`,time:new Date().toLocaleString()},...v]);setMsg(`${qty} ${lot.bloodGroup} unit(s) released to ZNBTS available stock.`);}catch(err){setError(err.message)}};
 const discard=e=>{e.preventDefault();clear();try{if(!regional&&!admin)throw new Error('Only ZNBTS users can discard central testing stock.'); const lot=inventoryLots.find(l=>l.id===form.sourceFacilityId); if(!lot||lot.facilityId!==ZNBTS_FACILITY_ID||!['Testing','Available'].includes(lot.status))throw new Error('Select a ZNBTS testing or available lot.');const qty=Number(lot.remaining);if(qty<1)throw new Error('Lot has no remaining units.');if(!form.reason)throw new Error('Disposition reason is required.');const fromTesting=lot.status==='Testing';const r=applyInventoryChange(networkInventory,{...znbts,bloodGroup:lot.bloodGroup,quantity:qty,deltaTesting:fromTesting?-qty:0,deltaAvailable:fromTesting?0:-qty,deltaDiscarded:qty,transactionType:'DISCARDED',referenceId:lot.id,performedBy:user.email});setNetworkInventory(r.rows);setInventoryLots(v=>v.map(x=>x.id===lot.id?{...x,remaining:0,status:INVENTORY_STATES.DISCARDED,dispositionReason:form.reason,updatedAt:new Date().toISOString()}:x));setInventoryTransactions(v=>[r.transaction,...v]);setAuditLogs(v=>[{id:createReference('AUD'),event:'Blood lot discarded',detail:`${qty} ${lot.bloodGroup} unit(s) discarded · ${form.reason}`,time:new Date().toLocaleString()},...v]);setMsg(`${qty} ${lot.bloodGroup} unit(s) discarded and removed from usable stock.`);}catch(err){setError(err.message)}};
 const adjust=e=>{e.preventDefault();clear();try{if(!regional&&!admin)throw new Error('Only ZNBTS users can adjust central stock.');const lot=inventoryLots.find(l=>l.id===form.sourceFacilityId);if(!lot)throw new Error('Select a lot.');const delta=Number(form.adjustment);if(!Number.isInteger(delta)||delta===0)throw new Error('Enter a non-zero adjustment.');if(!form.reason)throw new Error('Adjustment reason is required.');if(delta<0&&Math.abs(delta)>Number(lot.remaining))throw new Error('Adjustment exceeds lot balance.');const r=applyInventoryChange(networkInventory,{facilityId:lot.facilityId,facilityName:lot.facilityName,facilityType:'ZNBTS',province:'Copperbelt',district:'Kitwe',bloodGroup:lot.bloodGroup,quantity:Math.abs(delta),deltaAvailable:lot.status==='Available'?delta:0,deltaTesting:lot.status==='Testing'?delta:0,transactionType:'STOCK_ADJUSTMENT',referenceId:lot.id,performedBy:user.email});const nextRemaining=Number(lot.remaining)+delta;setNetworkInventory(r.rows);setInventoryLots(v=>v.map(x=>x.id===lot.id?{...x,quantity:Number(x.quantity)+delta,remaining:nextRemaining,updatedAt:new Date().toISOString()}:x));setInventoryTransactions(v=>[r.transaction,...v]);setAuditLogs(v=>[{id:createReference('AUD'),event:'Inventory stock adjustment',detail:`${lot.bloodGroup} ${delta>0?'+':''}${delta} unit(s) · ${form.reason}`,time:new Date().toLocaleString()},...v]);setMsg(`Stock adjusted by ${delta>0?'+':''}${delta} ${lot.bloodGroup}.`);}catch(err){setError(err.message)}};
 const title={collect:'Hospital Blood Collection','receive-testing':'Receive Hospital Blood for ZNBTS Testing','receive-external':'ZNBTS External Blood Intake',release:'Release Tested Blood','discard':'Discard Blood','adjust':'Reconcile / Adjust Stock'}[mode]||'Blood Inventory Operation';
 const selectedLots=mode==='receive-testing'?pendingLots:mode==='release'||mode==='discard'||mode==='adjust'?testingLots.concat(mode==='discard'||mode==='adjust'?inventoryLots.filter(l=>l.facilityId===ZNBTS_FACILITY_ID&&l.status===INVENTORY_STATES.AVAILABLE&&l.remaining>0):[]):[];
 const selectLabel=mode==='receive-testing'?'Pending hospital collection':mode==='release'?'ZNBTS testing lot':mode==='discard'?'ZNBTS lot':mode==='adjust'?'ZNBTS lot':'';
 const commonFields=<><label>Blood group<select name="bloodGroup" value={form.bloodGroup} onChange={update} className={input} required><option value="">Select</option>{GROUPS.map(g=><option key={g}>{g}</option>)}</select></label><label>Units<input name="units" type="number" min="1" value={form.units} onChange={update} className={input} required/></label><label>Collection date<input name="collectionDate" type="date" value={form.collectionDate} onChange={update} className={input} required/></label><label>Expiry date<input name="expiryDate" type="date" value={form.expiryDate} onChange={update} className={input}/></label></>;
 const lotSelect=selectedLots.length>0&&<label className="block">{selectLabel}<select name="sourceFacilityId" value={form.sourceFacilityId} onChange={update} className={input} required><option value="">Select lot</option>{selectedLots.map(l=><option key={l.id} value={l.id}>{l.id} · {l.bloodGroup} · {l.remaining} units · {l.facilityName}</option>)}</select></label>;
 const submitMap={collect:recordCollection,'receive-testing':receiveForTesting,'receive-external':externalReceive,release:releaseTesting,discard,adjust};
 return <div className="space-y-6 pb-10"><header><p className="text-sm font-bold uppercase tracking-wider text-[#8f1220]">UMULOPA Safe Transfer · ZNBTS Blood Service</p><h1 className="mt-2 text-3xl font-bold text-slate-900">{title}</h1><p className="mt-2 max-w-4xl text-slate-600">Every stock movement is recorded against a facility, lot, unit references, operator and transaction history. Available stock can only be created through an authorized release workflow.</p></header><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><form onSubmit={submitMap[mode]} className="grid gap-4 md:grid-cols-2">
 {mode==='collect'&&<>{commonFields}<label className="md:col-span-2">Collection/reference number<input name="collectionReference" value={form.collectionReference} onChange={update} className={input} placeholder="Collection batch/reference" required/></label><label className="md:col-span-2">Unit identifiers (optional; one per line or separated by commas)<textarea name="unitIdentifiers" value={form.unitIdentifiers} onChange={update} className={input} rows="3" placeholder="UNIT-001, UNIT-002"/></label><label className="md:col-span-2">Storage location<input name="storageLocation" value={form.storageLocation} onChange={update} className={input} placeholder="Hospital blood bank / refrigerator" required/></label></>}
 {mode==='receive-testing'&&<>{lotSelect}<label>Receiving date<input name="receivingDate" type="date" value={form.receivingDate} onChange={update} className={input} required/></label><label>Storage location<input name="storageLocation" value={form.storageLocation} onChange={update} className={input} required/></label></>}
 {mode==='receive-external'&&<>{commonFields}<label>Source facility<input name="sourceFacilityName" value={form.sourceFacilityName} onChange={update} className={input} required placeholder="External blood source"/></label><label>Source facility record<select name="sourceFacilityId" value={form.sourceFacilityId} onChange={update} className={input}><option value="">External / not in network</option>{sourceOptions.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label><label>Receiving date<input name="receivingDate" type="date" value={form.receivingDate} onChange={update} className={input} required/></label><label>Storage location<input name="storageLocation" value={form.storageLocation} onChange={update} className={input} required/></label><label>Collection/reference number<input name="collectionReference" value={form.collectionReference} onChange={update} className={input}/></label><label>Unit identifiers<textarea name="unitIdentifiers" value={form.unitIdentifiers} onChange={update} className={input} rows="2"/></label><label className="md:col-span-2">Testing/reference number<input name="testingReference" value={form.testingReference} onChange={update} className={input} required/></label></>}
 {mode==='release'&&<>{lotSelect}<label>Testing reference/result number<input name="testingReference" value={form.testingReference} onChange={update} className={input} required/></label><label>Test result<select name="testResult" value={form.testResult} onChange={update} className={input} required><option value="">Select</option><option value="PASS">PASS — Release to available</option><option value="FAIL">FAIL — Do not release</option></select></label></>}
 {mode==='discard'&&<>{lotSelect}<label className="md:col-span-2">Disposition reason<textarea name="reason" value={form.reason} onChange={update} className={input} rows="3" required placeholder="Reason and authorization reference"/></label></>}
 {mode==='adjust'&&<>{lotSelect}<label>Adjustment (+/- units)<input name="adjustment" type="number" value={form.adjustment} onChange={update} className={input} required/></label><label className="md:col-span-2">Reconciliation reason<textarea name="reason" value={form.reason} onChange={update} className={input} rows="3" required placeholder="Physical count / data correction reason"/></label></>}
 <div className="md:col-span-2 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-900">{mode==='collect'?'Collection is recorded as Testing or Awaiting ZNBTS Testing according to the hospital capability granted by ZNBTS.':mode==='receive-testing'?'Receiving moves the complete lot from the hospital pending queue into ZNBTS Testing. It does not create available stock.':mode==='receive-external'?'External intake enters ZNBTS Testing. It cannot become Available until an authorized testing/release operation records a PASS result.':mode==='release'?'Only a recorded PASS releases the lot from Testing to Available.':mode==='discard'?'Discarded units are removed from Testing or Available stock and permanently marked Discarded.': 'Adjust Stock is restricted to reconciliation and creates an audit transaction.'}</div>
 {error&&<p className="md:col-span-2 font-semibold text-red-700">{error}</p>}{msg&&<p className="md:col-span-2 font-semibold text-emerald-700">{msg}</p>}
 <div className="md:col-span-2 flex flex-wrap gap-3"><button type="submit" className="rounded-xl bg-[#8f1220] px-6 py-3 font-bold text-white">Complete operation</button><button type="button" onClick={()=>navigate('/inventory')} className="rounded-xl border px-6 py-3 font-semibold">Cancel</button></div>
 </form></div></div>;
}
